apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: maas-api-data
  namespace: maas-api
  labels:
    app.kubernetes.io/name: maas-api
    app.kubernetes.io/component: storage
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
